Завершает верстку hero и добавляет анимацию
Anastasiia-Tarasiuk/ice-cream-page pull request #18
Opened 2022-01-29 21:36 UTC by Anastasiia-Tarasiuk

2022-01-29 22:38 UTC, Danila-Fateev requested changes
1. Удалить nav-bar
2. Спозиционировать div class="hero__wrap"

2022-01-29 22:38 UTC, Danila-Fateev commented on src/partials/hero.html
> +        <div class="nav-bar">ТУТ МЕНЮ</div>
nav-bar нужно удалить, он относиться к хедеру, а не к хиро

2022-01-29 22:38 UTC, Danila-Fateev commented on src/partials/hero.html
> +            </h1>
Надо абсолютно спозиционировать на tablet и mobile версиях сайта через `div class="hero__wrap"` также, как ты это делала на десктопной версии , а ты маржинами от nav-bar толкала)

2022-01-30 08:35 UTC, Anastasiia-Tarasiuk commented on src/partials/hero.html
> +            </h1>
Сделала

2022-01-30 08:36 UTC, Anastasiia-Tarasiuk commented on src/partials/hero.html
> +        <div class="nav-bar">ТУТ МЕНЮ</div>
Сделала

2022-01-30 08:38 UTC, Danila-Fateev approved these changes

2022-01-30 08:40 UTC, merged