features/advantages
Anastasiia-Tarasiuk/ice-cream-page pull request #19
Opened 2022-01-29 23:12 UTC by Katya2211

2022-01-30 19:37 UTC, Danila-Fateev requested changes

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 320px) and (max-width: 767px) {
В значении min-width: 320px нет необходимости, надо это убрать

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 320px) and (max-width: 767px) {
min-width: 320px тут убрать тоже

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 320px) and (max-width: 767px) {
min-width: 320px тут убрать тоже

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 320px) and (max-width: 767px) {
min-width: 320px тут убрать тоже

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 320px) and (max-width: 767px) {
min-width: 320px тут убрать тоже

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1199px) {
должно быть max-width: 1279px так как
Точка перелома 1280px, а не 1200px

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1200px) {
Точка перелома 1280px, а не 1200px

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1199px) {
должно быть max-width: 1279px так как
Точка перелома 1280px, а не 1200px

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1200px) {
Точка перелома 1280px, а не 1200px

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  margin-bottom: 65px;
margin-bottom для планшетной и десктопной версии надо обнулить, а также для последнего потомка через :last-child в мобильной версии сайта

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  margin-right: 30px;
margin-right на мобильной версии сайта должен быть равен нулю, и только начиная с планшетной должен равняться 30px

2022-01-30 19:37 UTC, Danila-Fateev commented on src/partials/advantages.html
> +    <div class="advantages-box container">
Ты в стилизации не используешь класс advantages-box, удали его

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  background-color: $background-color;
надо добавить нижные паддинги для секции, верхнии необязателно 
Советую сделать это так:
.advantages__section {
background-color: $background-color;

@include section-padding(0, 97px);

@media screen and (min-width: 768px){
@include section-padding(0, 140px);
}
}

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  font-style: normal;
font-weight: normal; и  font-style: normal; здесь в них нет необходимости, они просто засоряют код
Удалить

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  height: 52px;
- font-family: DM Sans; шрифт указан для всей страницы в base.scss, здесь он ничего не делает, нужно убрать эту строчку
- font-style: normal; убрать, засоряет код
- font-weight: bold; вместо bold напиши 700
- - font-weight: bold; повторяется дважды на 74 и 78 строке, надо оставить только один
- height: 52px; высота должна определяться по контенту, а не чётко задаваться (исключение: картинки, свг-спрайты и т.д.), удалить

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +    height: 67px;
высота лишняя

2022-01-30 19:37 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +.advantages {
Список должен быть стилизован, как сетка элементов, как портфолио в нашем дз

2022-01-31 16:48 UTC, Danila-Fateev requested changes

2022-01-31 16:48 UTC, Danila-Fateev commented on src/partials/advantages.html
> +    <div class="advantages-box container">
<div class="advantages-box container"> этот класс ты не использовала нигде, он просто засоряет код, убери его

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  flex-direction: row;
нет смысла в flex-direction: row; так как на мобильной версии всё и так идёт в столбик 
удали flex-direction: row;

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  padding-top: 39px;
padding-top: 39px; не нужен здесь , если хочешь сделать верхний отступ, то делай паддинг для секции
.advantages__section {
  background-color: $background-color;
  @include section-padding(0, 97px);
  @media screen and (min-width: 768px) {
    @include section-padding(0, 140px);
  }
}
Вместо нуля поставь значение, которое соответствует верхнему отступу в макете, но это необязательно 
Удали padding-top: 39px;

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +    padding-top: 66px;
Про паддинг тоже самое, что я писал чуть выше
удали его

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1279px) {
Может я ошибься в чём-то, когда писал ревью в прошлый раз, но изменения для десктопной версии сайта должны начинаться с 1280px, a не c 1279px

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +    margin-right: 66px;
margin-left: 16px;
    margin-right: 66px;
Не совсем понял для чего здесь нужны, если список должен был встать по середине, то надо использовать  justify-content: center; , а если ты хотела, чтобы список встал в начале строки, то лучше использовать justify-content: flex-start;

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +    margin-right: 100px;
тоже самое, что я писал про маржины чуть выше, если ты в прошлом исправила маржины на justify-content: flex-start;, то здесь надо будет написать justify-content: center;, чтобы они встали по середине

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +    padding-bottom: 13px;
отступы между элементами задаются через маржины, а через падинги в исколючительных случаях
поменяй padding-bottom: 13px; на margin-bottom: 13px;

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1278px) {
в and (max-width: 1278px) нет смысла убери или поменяй на and (max-width: 1279px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1279px) {
должно быть and (min-width: 1280px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1278px) {
в and (max-width: 1278px) нет смысла убери или поменяй на and (max-width: 1279px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1279px) {
должно быть and (min-width: 1280px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1278px) {
в and (max-width: 1278px) нет смысла убери

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +    width: 100%;
Не понял зачем ты элемент списка растягиваешь на всю ширину

Список должен быть сделан, как сетка элементов у нас в портофолио в домашних заданиях, и ширина списка элемента должна определяться по формуле

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +    width: 100%;
Если ты выше убрала and (max-width: 1278px), то это медиа-правило можно убрать

должно быть and (min-width: 1280px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1278px) {
в and (max-width: 1278px) нет смысла убери или поменяй на and (max-width: 1279px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1279px) {
должно быть and (min-width: 1280px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1278px) {
в and (max-width: 1278px) нет смысла убери или поменяй на and (max-width: 1279px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1278px) {
в and (max-width: 1278px) нет смысла убери или поменяй на and (max-width: 1279px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 768px) and (max-width: 1278px) {
в and (max-width: 1278px) нет смысла убери или поменяй на and (max-width: 1279px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1279px) {
должно быть and (min-width: 1280px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1279px) {
должно быть and (min-width: 1280px)

2022-01-31 16:48 UTC, Danila-Fateev commented on src/sass/components/_advantages.scss
> +  @media screen and (min-width: 1279px) {
должно быть and (min-width: 1280px)

2022-01-31 19:27 UTC, Anastasiia-Tarasiuk approved these changes

2022-01-31 19:29 UTC, Anastasiia-Tarasiuk approved these changes

2022-01-31 19:31 UTC, Anastasiia-Tarasiuk approved these changes

2022-01-31 19:32 UTC, Anastasiia-Tarasiuk approved these changes

2022-01-31 19:32 UTC, merged